import type { DoctorVideo } from "@/types";
import { videoSlugsForHairTransplantPage } from "@/lib/api/hair-transplant-variants";
import { applyMockDelay } from "./mock-delay";

/**
 * Doctor-anchored treatment videos. Every entry must reference a real
 * doctor.id and a real treatment.slug; otherwise the video is silently
 * skipped at render time. Sourced from verified doctor channels only —
 * generic stock content does not belong here.
 */
const DOCTOR_VIDEOS: DoctorVideo[] = [
  {
    id: "mahmoud_hafez_v1",
    source: "youtube",
    embedRef: "7_s1DnsYS50",
    canonicalUrl: "https://www.youtube.com/watch?v=7_s1DnsYS50",
    doctorId: "mahmoud_hafez",
    treatmentSlug: "knee-replacement",
    captionKey: "videos.items.mahmoud_hafez_v1.caption",
    publishedAt: "2016-07-01",
  },
  {
    id: "mohamed_mohi_eldin_v1",
    source: "youtube",
    embedRef: "DisvTbOgGlU",
    canonicalUrl: "https://www.youtube.com/watch?v=DisvTbOgGlU",
    doctorId: "mohamed_mohi_eldin",
    treatmentSlug: "spine-surgery",
    captionKey: "videos.items.mohamed_mohi_eldin_v1.caption",
    publishedAt: "2016-10-21",
  },
  {
    id: "mohamed_mohi_eldin_v2",
    source: "youtube",
    embedRef: "e-8lKRIL7UU",
    canonicalUrl: "https://www.youtube.com/watch?v=e-8lKRIL7UU",
    doctorId: "mohamed_mohi_eldin",
    treatmentSlug: "spine-surgery",
    captionKey: "videos.items.mohamed_mohi_eldin_v2.caption",
    publishedAt: "2015-05-13",
  },
  {
    id: "mohamed_mokhtar_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/ProfMohamedMokhtar/videos/1468160374301062/",
    canonicalUrl: "https://www.facebook.com/ProfMohamedMokhtar/videos/1468160374301062/",
    doctorId: "mohamed_mokhtar",
    treatmentSlug: "ankle-surgery",
    captionKey: "videos.items.mohamed_mokhtar_v1.caption",
    publishedAt: "2024-06-01",
  },
  {
    id: "mohamed_mokhtar_v2",
    source: "facebook",
    embedRef: "https://www.facebook.com/ProfMohamedMokhtar/videos/989174062612591/",
    canonicalUrl: "https://www.facebook.com/ProfMohamedMokhtar/videos/989174062612591/",
    doctorId: "mohamed_mokhtar",
    treatmentSlug: "ankle-surgery",
    captionKey: "videos.items.mohamed_mokhtar_v2.caption",
    publishedAt: "2023-09-01",
  },
  {
    id: "nasef_mohamed_nasef_v1",
    source: "instagram",
    embedRef: "reel/DOttJH5kiLq",
    canonicalUrl: "https://www.instagram.com/reel/DOttJH5kiLq/",
    doctorId: "nasef_mohamed_nasef",
    treatmentSlug: "ankle-surgery",
    captionKey: "videos.items.nasef_mohamed_nasef_v1.caption",
    publishedAt: "2025-08-01",
  },
  {
    id: "nasef_mohamed_nasef_v2",
    source: "instagram",
    embedRef: "reel/DI6cTuLoPK2",
    canonicalUrl: "https://www.instagram.com/reel/DI6cTuLoPK2/",
    doctorId: "nasef_mohamed_nasef",
    treatmentSlug: "ankle-surgery",
    captionKey: "videos.items.nasef_mohamed_nasef_v2.caption",
    publishedAt: "2025-04-15",
  },
  {
    id: "yasser_batrawy_v1",
    source: "youtube",
    embedRef: "nujGRvk0MoI",
    canonicalUrl: "https://www.youtube.com/watch?v=nujGRvk0MoI",
    doctorId: "yasser_batrawy",
    treatmentSlug: "limb-lengthening",
    captionKey: "videos.items.yasser_batrawy_v1.caption",
    publishedAt: "2017-12-01",
  },
  {
    id: "yasser_batrawy_v2",
    source: "youtube",
    embedRef: "6sJBvP1jdIU",
    canonicalUrl: "https://www.youtube.com/watch?v=6sJBvP1jdIU",
    doctorId: "yasser_batrawy",
    treatmentSlug: "limb-lengthening",
    captionKey: "videos.items.yasser_batrawy_v2.caption",
    publishedAt: "2018-03-15",
  },
  {
    id: "yasser_batrawy_v3",
    source: "youtube",
    embedRef: "ha4MY-XMv3w",
    canonicalUrl: "https://www.youtube.com/watch?v=ha4MY-XMv3w",
    doctorId: "yasser_batrawy",
    treatmentSlug: "limb-lengthening",
    captionKey: "videos.items.yasser_batrawy_v3.caption",
    publishedAt: "2019-05-10",
  },
  {
    id: "yasser_sadek_v1",
    source: "youtube",
    embedRef: "rtpd5CJzUAc",
    canonicalUrl: "https://www.youtube.com/watch?v=rtpd5CJzUAc",
    doctorId: "yasser_sadek",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.yasser_sadek_v1.caption",
    publishedAt: "2021-05-15",
  },
  {
    id: "yasser_sadek_v2",
    source: "youtube",
    embedRef: "sGPYXQvA6vo",
    canonicalUrl: "https://www.youtube.com/watch?v=sGPYXQvA6vo",
    doctorId: "yasser_sadek",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.yasser_sadek_v2.caption",
    publishedAt: "2019-03-10",
  },
  {
    id: "yasser_sadek_v3",
    source: "youtube",
    embedRef: "mAW5wnTfY2E",
    canonicalUrl: "https://www.youtube.com/watch?v=mAW5wnTfY2E",
    doctorId: "yasser_sadek",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.yasser_sadek_v3.caption",
    publishedAt: "2019-06-20",
  },
  {
    id: "ayman_mortada_v1",
    source: "youtube",
    embedRef: "dcsHqZs4Kqs",
    canonicalUrl: "https://www.youtube.com/watch?v=dcsHqZs4Kqs",
    doctorId: "ayman_mortada",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.ayman_mortada_v1.caption",
    publishedAt: "2019-04-19",
  },
  {
    id: "ayman_mortada_v2",
    source: "youtube",
    embedRef: "5YbZbIZOOTA",
    canonicalUrl: "https://www.youtube.com/watch?v=5YbZbIZOOTA",
    doctorId: "ayman_mortada",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.ayman_mortada_v2.caption",
    publishedAt: "2019-10-02",
  },
  {
    id: "nabil_farag_v1",
    source: "youtube",
    embedRef: "Pl0CPs8jxog",
    canonicalUrl: "https://www.youtube.com/watch?v=Pl0CPs8jxog",
    doctorId: "nabil_farag",
    treatmentSlug: "cardiology",
    captionKey: "videos.items.nabil_farag_v1.caption",
    publishedAt: "2020-10-29",
  },
  {
    id: "tarek_helmy_v1",
    source: "youtube",
    embedRef: "YNV33x6LtiQ",
    canonicalUrl: "https://www.youtube.com/watch?v=YNV33x6LtiQ",
    doctorId: "tarek_helmy",
    treatmentSlug: "cardiac-surgery",
    captionKey: "videos.items.tarek_helmy_v1.caption",
    publishedAt: "2018-09-30",
  },
  {
    id: "hesham_elghazaly_v1",
    source: "youtube",
    embedRef: "FNfFHs0tcZc",
    canonicalUrl: "https://www.youtube.com/watch?v=FNfFHs0tcZc",
    doctorId: "hesham_elghazaly",
    treatmentSlug: "oncology",
    captionKey: "videos.items.hesham_elghazaly_v1.caption",
    publishedAt: "2025-01-27",
  },
  {
    id: "hesham_elghazaly_v2",
    source: "youtube",
    embedRef: "OqBfvBsEEVs",
    canonicalUrl: "https://www.youtube.com/watch?v=OqBfvBsEEVs",
    doctorId: "hesham_elghazaly",
    treatmentSlug: "oncology",
    captionKey: "videos.items.hesham_elghazaly_v2.caption",
    publishedAt: "2024-10-10",
  },
  {
    id: "hesham_elghazaly_v3",
    source: "youtube",
    embedRef: "s4Lq4W-PXOU",
    canonicalUrl: "https://www.youtube.com/watch?v=s4Lq4W-PXOU",
    doctorId: "hesham_elghazaly",
    treatmentSlug: "oncology",
    captionKey: "videos.items.hesham_elghazaly_v3.caption",
    publishedAt: "2018-01-29",
  },
  {
    id: "hatem_azim_v1",
    source: "youtube",
    embedRef: "-9AjTmHk3hs",
    canonicalUrl: "https://www.youtube.com/watch?v=-9AjTmHk3hs",
    doctorId: "hatem_azim",
    treatmentSlug: "oncology",
    captionKey: "videos.items.hatem_azim_v1.caption",
    publishedAt: "2024-08-26",
  },
  {
    id: "hatem_azim_v2",
    source: "youtube",
    embedRef: "NsxyAPGr-6c",
    canonicalUrl: "https://www.youtube.com/watch?v=NsxyAPGr-6c",
    doctorId: "hatem_azim",
    treatmentSlug: "oncology",
    captionKey: "videos.items.hatem_azim_v2.caption",
    publishedAt: "2023-12-07",
  },
  {
    id: "dina_zamzam_v1",
    source: "youtube",
    embedRef: "UzZ-4zCTzfk",
    canonicalUrl: "https://www.youtube.com/watch?v=UzZ-4zCTzfk",
    doctorId: "dina_zamzam",
    treatmentSlug: "neurology",
    captionKey: "videos.items.dina_zamzam_v1.caption",
    publishedAt: "2022-02-01",
  },
  {
    id: "dina_zamzam_v2",
    source: "youtube",
    embedRef: "KJnIYpQNuWg",
    canonicalUrl: "https://www.youtube.com/watch?v=KJnIYpQNuWg",
    doctorId: "dina_zamzam",
    treatmentSlug: "neurology",
    captionKey: "videos.items.dina_zamzam_v2.caption",
    publishedAt: "2023-05-01",
  },
  {
    id: "mostafada_farid_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/mostafa.farid.inr/videos/272744436696381/",
    canonicalUrl: "https://www.facebook.com/mostafa.farid.inr/videos/272744436696381/",
    doctorId: "mostafada_farid",
    treatmentSlug: "neurology",
    captionKey: "videos.items.mostafada_farid_v1.caption",
    publishedAt: "2021-06-15",
  },
  {
    id: "osama_alghanam_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/neurocentereg/videos/1475820649231989/",
    canonicalUrl: "https://www.facebook.com/neurocentereg/videos/1475820649231989/",
    doctorId: "osama_alghanam",
    treatmentSlug: "neurosurgery",
    captionKey: "videos.items.osama_alghanam_v1.caption",
    publishedAt: "2022-03-10",
  },
  {
    id: "osama_alghanam_v2",
    source: "facebook",
    embedRef: "https://www.facebook.com/neurocentereg/videos/348278196223439/",
    canonicalUrl: "https://www.facebook.com/neurocentereg/videos/348278196223439/",
    doctorId: "osama_alghanam",
    treatmentSlug: "neurosurgery",
    captionKey: "videos.items.osama_alghanam_v2.caption",
    publishedAt: "2021-11-20",
  },
  {
    id: "ahmed_zahran_v1",
    source: "instagram",
    embedRef: "reel/C_hqFFuNXIg",
    canonicalUrl: "https://www.instagram.com/reel/C_hqFFuNXIg/",
    doctorId: "ahmed_zahran",
    treatmentSlug: "neurosurgery",
    captionKey: "videos.items.ahmed_zahran_v1.caption",
    publishedAt: "2024-09-05",
  },
  {
    id: "ahmed_zahran_v2",
    source: "youtube",
    embedRef: "KNBCCN665VI",
    canonicalUrl: "https://www.youtube.com/watch?v=KNBCCN665VI",
    doctorId: "ahmed_zahran",
    treatmentSlug: "neurosurgery",
    captionKey: "videos.items.ahmed_zahran_v2.caption",
    publishedAt: "2021-04-12",
  },
  {
    id: "ahmed_zahran_v3",
    source: "youtube",
    embedRef: "V5MRo5WS1Ys",
    canonicalUrl: "https://www.youtube.com/watch?v=V5MRo5WS1Ys",
    doctorId: "ahmed_zahran",
    treatmentSlug: "neurosurgery",
    captionKey: "videos.items.ahmed_zahran_v3.caption",
    publishedAt: "2021-05-20",
  },
  {
    id: "tamer_abdelbaki_v1",
    source: "youtube",
    embedRef: "pzk0ko_q9c0",
    canonicalUrl: "https://www.youtube.com/watch?v=pzk0ko_q9c0",
    doctorId: "tamer_abdelbaki",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.tamer_abdelbaki_v1.caption",
    publishedAt: "2017-06-01",
  },
  {
    id: "tamer_abdelbaki_v2",
    source: "youtube",
    embedRef: "gDnReoKNYUM",
    canonicalUrl: "https://www.youtube.com/watch?v=gDnReoKNYUM",
    doctorId: "tamer_abdelbaki",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.tamer_abdelbaki_v2.caption",
    publishedAt: "2016-11-01",
  },
  {
    id: "tamer_abdelbaki_v3",
    source: "youtube",
    embedRef: "5vLviu2tAzs",
    canonicalUrl: "https://www.youtube.com/watch?v=5vLviu2tAzs",
    doctorId: "tamer_abdelbaki",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.tamer_abdelbaki_v3.caption",
    publishedAt: "2020-02-01",
  },
  {
    id: "osama_taha_v1",
    source: "youtube",
    embedRef: "7S-Tp6nVFSs",
    canonicalUrl: "https://www.youtube.com/watch?v=7S-Tp6nVFSs",
    doctorId: "osama_taha",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.osama_taha_v1.caption",
    publishedAt: "2018-01-01",
  },
  {
    id: "osama_taha_v2",
    source: "youtube",
    embedRef: "u-YZr1UhppM",
    canonicalUrl: "https://www.youtube.com/watch?v=u-YZr1UhppM",
    doctorId: "osama_taha",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.osama_taha_v2.caption",
    publishedAt: "2018-05-01",
  },
  {
    id: "khaled_gawdat_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/Obesityegclinic/videos/844717197134194/",
    canonicalUrl: "https://www.facebook.com/Obesityegclinic/videos/844717197134194/",
    doctorId: "khaled_gawdat",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.khaled_gawdat_v1.caption",
    publishedAt: "2022-03-01",
  },
  {
    id: "khaled_gawdat_v2",
    source: "facebook",
    embedRef: "https://www.facebook.com/Obesityegclinic/videos/205485345971843/",
    canonicalUrl: "https://www.facebook.com/Obesityegclinic/videos/205485345971843/",
    doctorId: "khaled_gawdat",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.khaled_gawdat_v2.caption",
    publishedAt: "2021-09-01",
  },
  {
    id: "khaled_gawdat_v3",
    source: "facebook",
    embedRef: "https://www.facebook.com/Obesityegclinic/videos/319312362843052/",
    canonicalUrl: "https://www.facebook.com/Obesityegclinic/videos/319312362843052/",
    doctorId: "khaled_gawdat",
    treatmentSlug: "bariatric",
    captionKey: "videos.items.khaled_gawdat_v3.caption",
    publishedAt: "2022-08-01",
  },
  {
    id: "nasser_loza_v1",
    source: "youtube",
    embedRef: "70_i258sBTk",
    canonicalUrl: "https://www.youtube.com/watch?v=70_i258sBTk",
    doctorId: "nasser_loza",
    treatmentSlug: "addiction",
    captionKey: "videos.items.nasser_loza_v1.caption",
    publishedAt: "2023-04-13",
  },
  {
    id: "mohamed_aboulghar_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/egyptianivfcenter/videos/ivf/1595202174799504/",
    canonicalUrl: "https://www.facebook.com/egyptianivfcenter/videos/ivf/1595202174799504/",
    doctorId: "mohamed_aboulghar",
    treatmentSlug: "ivf",
    captionKey: "videos.items.mohamed_aboulghar_v1.caption",
    publishedAt: "2024-06-01",
  },
  {
    id: "yasser_badi_v1",
    source: "instagram",
    embedRef: "reel/DBhIrZWN2AA",
    canonicalUrl: "https://www.instagram.com/dryasserbadi/reel/DBhIrZWN2AA/",
    doctorId: "yasser_badi",
    treatmentSlug: "vaser-liposuction",
    captionKey: "videos.items.yasser_badi_v1.caption",
    publishedAt: "2024-10-23",
  },
  {
    id: "yasser_badi_v2",
    source: "instagram",
    embedRef: "reel/DAQ4xsYNV0-",
    canonicalUrl: "https://www.instagram.com/dryasserbadi/reel/DAQ4xsYNV0-/",
    doctorId: "yasser_badi",
    treatmentSlug: "breast-augmentation",
    captionKey: "videos.items.yasser_badi_v2.caption",
    publishedAt: "2024-09-25",
  },
  {
    id: "yasser_badi_v3",
    source: "instagram",
    embedRef: "reel/DDaKSrrIUAr",
    canonicalUrl: "https://www.instagram.com/dryasserbadi/reel/DDaKSrrIUAr/",
    doctorId: "yasser_badi",
    treatmentSlug: "cosmetic",
    captionKey: "videos.items.yasser_badi_v3.caption",
    publishedAt: "2024-12-30",
  },
  {
    id: "marwan_noureldin_v1",
    source: "instagram",
    embedRef: "reel/DRCvZn3jAFj",
    canonicalUrl: "https://www.instagram.com/dr.marwan_noureldin/reel/DRCvZn3jAFj/",
    doctorId: "marwan_noureldin",
    treatmentSlug: "hair-transplant",
    captionKey: "videos.items.marwan_noureldin_v1.caption",
    publishedAt: "2025-09-15",
  },
  {
    id: "marwan_noureldin_v2",
    source: "instagram",
    embedRef: "reel/DAsiO8dNRNQ",
    canonicalUrl: "https://www.instagram.com/dr.marwan_noureldin/reel/DAsiO8dNRNQ/",
    doctorId: "marwan_noureldin",
    treatmentSlug: "hair-transplant",
    captionKey: "videos.items.marwan_noureldin_v2.caption",
    publishedAt: "2024-10-01",
  },
  {
    id: "marwan_noureldin_v3",
    source: "instagram",
    embedRef: "reel/C2XtHpoLcJV",
    canonicalUrl: "https://www.instagram.com/dr.marwan_noureldin/reel/C2XtHpoLcJV/",
    doctorId: "marwan_noureldin",
    treatmentSlug: "hair-transplant",
    captionKey: "videos.items.marwan_noureldin_v3.caption",
    publishedAt: "2024-01-25",
  },
  {
    id: "hossam_tahseen_v1",
    source: "youtube",
    embedRef: "vIl61xNhE4U",
    canonicalUrl: "https://www.youtube.com/watch?v=vIl61xNhE4U",
    doctorId: "hossam_tahseen",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.hossam_tahseen_v1.caption",
    publishedAt: "2020-10-15",
  },
  {
    id: "hossam_tahseen_v2",
    source: "instagram",
    embedRef: "reel/DCzh0ZGueNA",
    canonicalUrl: "https://www.instagram.com/hossamtahseen/reel/DCzh0ZGueNA/",
    doctorId: "hossam_tahseen",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.hossam_tahseen_v2.caption",
    publishedAt: "2024-12-10",
  },
  {
    id: "mohamed_elghalban_v1",
    source: "instagram",
    embedRef: "p/CteuqhXLW-2",
    canonicalUrl: "https://www.instagram.com/p/CteuqhXLW-2/",
    doctorId: "mohamed_elghalban",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.mohamed_elghalban_v1.caption",
    publishedAt: "2023-06-21",
  },
  {
    id: "mohamed_mamdouh_v1",
    source: "facebook",
    embedRef: "https://www.facebook.com/dr.mohmamdouh/videos/1173714102973513/",
    canonicalUrl: "https://www.facebook.com/dr.mohmamdouh/videos/1173714102973513/",
    doctorId: "mohamed_mamdouh",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.mohamed_mamdouh_v1.caption",
    publishedAt: "2023-05-10",
  },
  {
    id: "samir_ghoraba_v1",
    source: "instagram",
    embedRef: "reel/C_8s9tVtYrX",
    canonicalUrl: "https://www.instagram.com/samirghoraba/reel/C_8s9tVtYrX/",
    doctorId: "samir_ghoraba",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.samir_ghoraba_v1.caption",
    publishedAt: "2024-09-20",
  },
  {
    id: "samir_ghoraba_v2",
    source: "instagram",
    embedRef: "reel/C_25Oa6NUmo",
    canonicalUrl: "https://www.instagram.com/samirghoraba/reel/C_25Oa6NUmo/",
    doctorId: "samir_ghoraba",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.samir_ghoraba_v2.caption",
    publishedAt: "2024-09-18",
  },
  {
    id: "samir_ghoraba_v3",
    source: "instagram",
    embedRef: "reel/C_EDL87N0wA",
    canonicalUrl: "https://www.instagram.com/samirghoraba/reel/C_EDL87N0wA/",
    doctorId: "samir_ghoraba",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.samir_ghoraba_v3.caption",
    publishedAt: "2024-08-29",
  },
  {
    id: "khaled_sami_v1",
    source: "instagram",
    embedRef: "reel/C8m6bdsM0PZ",
    canonicalUrl: "https://www.instagram.com/dr.khaledsami/reel/C8m6bdsM0PZ/",
    doctorId: "khaled_sami",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.khaled_sami_v1.caption",
    publishedAt: "2024-07-04",
  },
  {
    id: "khaled_sami_v2",
    source: "instagram",
    embedRef: "reel/C2VYOxgMZPh",
    canonicalUrl: "https://www.instagram.com/dr.khaledsami/reel/C2VYOxgMZPh/",
    doctorId: "khaled_sami",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.khaled_sami_v2.caption",
    publishedAt: "2024-01-26",
  },
  {
    id: "khaled_sami_v3",
    source: "instagram",
    embedRef: "reel/CuM0H-2gFwH",
    canonicalUrl: "https://www.instagram.com/dr.khaledsami/reel/CuM0H-2gFwH/",
    doctorId: "khaled_sami",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.khaled_sami_v3.caption",
    publishedAt: "2023-07-13",
  },
  {
    id: "wael_ghannem_v1",
    source: "instagram",
    embedRef: "reel/DPy6vsRiMrg",
    canonicalUrl: "https://www.instagram.com/reel/DPy6vsRiMrg/",
    doctorId: "wael_ghannem",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.wael_ghannem_v1.caption",
    publishedAt: "2025-09-30",
  },
  {
    id: "wael_ghannem_v2",
    source: "instagram",
    embedRef: "reel/DNadapis5vB",
    canonicalUrl: "https://www.instagram.com/reel/DNadapis5vB/",
    doctorId: "wael_ghannem",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.wael_ghannem_v2.caption",
    publishedAt: "2025-08-05",
  },
  {
    id: "ashraf_abolfotoh_v1",
    source: "instagram",
    embedRef: "p/CtzWhWgrO8Q",
    canonicalUrl: "https://www.instagram.com/p/CtzWhWgrO8Q/",
    doctorId: "ashraf_abolfotoh",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.ashraf_abolfotoh_v1.caption",
    publishedAt: "2023-06-25",
  },
  {
    id: "hossam_abolatta_v1",
    source: "youtube",
    embedRef: "m0zUFjQ9BZg",
    canonicalUrl: "https://www.youtube.com/watch?v=m0zUFjQ9BZg",
    doctorId: "hossam_abolatta",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.hossam_abolatta_v1.caption",
    publishedAt: "2021-08-12",
  },
  {
    id: "ahmed_taalab_v1",
    source: "instagram",
    embedRef: "p/DCcjblBOaF1",
    canonicalUrl: "https://www.instagram.com/p/DCcjblBOaF1/",
    doctorId: "ahmed_taalab",
    treatmentSlug: "plastic-surgery",
    captionKey: "videos.items.ahmed_taalab_v1.caption",
    publishedAt: "2024-11-20",
  },
];

export async function listDoctorVideos(options?: { simulateDelay?: boolean }): Promise<DoctorVideo[]> {
  await applyMockDelay(options?.simulateDelay);
  return [...DOCTOR_VIDEOS];
}

/** Newest first. */
export async function getVideosForTreatment(
  treatmentSlug: string,
  options?: { simulateDelay?: boolean },
): Promise<DoctorVideo[]> {
  await applyMockDelay(options?.simulateDelay);
  const hairSlugs = videoSlugsForHairTransplantPage();
  return DOCTOR_VIDEOS
    .filter((v) =>
      treatmentSlug === "hair-transplant" ? hairSlugs.has(v.treatmentSlug) : v.treatmentSlug === treatmentSlug,
    )
    .sort((a, b) => (b.publishedAt ?? "").localeCompare(a.publishedAt ?? ""));
}

export async function getVideosByDoctor(
  doctorId: string,
  options?: { simulateDelay?: boolean },
): Promise<DoctorVideo[]> {
  await applyMockDelay(options?.simulateDelay);
  return DOCTOR_VIDEOS.filter((v) => v.doctorId === doctorId);
}

/** Embed URL helpers per source. */
export function videoEmbedSrc(v: DoctorVideo): string {
  switch (v.source) {
    case "youtube":
      return `https://www.youtube.com/embed/${v.embedRef}`;
    case "instagram":
      return `https://www.instagram.com/${v.embedRef}/embed`;
    case "facebook":
      return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(v.canonicalUrl)}&show_text=false`;
  }
}
