import type { Treatment } from "@/types";
import { applyMockDelay } from "./mock-delay";

const TREATMENTS: Treatment[] = [
  {
    id: "diabetic_foot",
    slug: "diabetic-foot",
    sortOrder: 1,
    category: "general",
    titleKey: "treatments.items.diabetic_foot.title",
    descriptionKey: "treatments.items.diabetic_foot.description",
    bodyKey: "treatments.items.diabetic_foot.body",
    doctorsKey: "treatments.items.diabetic_foot.doctors",
    hospitalsKey: "treatments.items.diabetic_foot.hospitals",
    techniquesKey: "treatments.items.diabetic_foot.techniques",
    successRateKey: "treatments.items.diabetic_foot.success_rate",
    videoUrlKey: "treatments.items.diabetic_foot.video_url",
    doctorIds: ["rashad_bishara", "ayman_samadony", "hussein_alwan"],
    priceUSD: 1500,
  },
  {
    id: "ivf",
    slug: "ivf",
    sortOrder: 2,
    category: "general",
    titleKey: "treatments.items.ivf.title",
    descriptionKey: "treatments.items.ivf.description",
    bodyKey: "treatments.items.ivf.body",
    doctorsKey: "treatments.items.ivf.doctors",
    hospitalsKey: "treatments.items.ivf.hospitals",
    techniquesKey: "treatments.items.ivf.techniques",
    successRateKey: "treatments.items.ivf.success_rate",
    videoUrlKey: "treatments.items.ivf.video_url",
    doctorIds: ["mohamed_aboulghar", "maged_adel_aziz"],
    priceUSD: 2000,
  },
  {
    id: "oncology",
    slug: "oncology",
    sortOrder: 3,
    category: "general",
    titleKey: "treatments.items.oncology.title",
    descriptionKey: "treatments.items.oncology.description",
    bodyKey: "treatments.items.oncology.body",
    doctorsKey: "treatments.items.oncology.doctors",
    hospitalsKey: "treatments.items.oncology.hospitals",
    techniquesKey: "treatments.items.oncology.techniques",
    successRateKey: "treatments.items.oncology.success_rate",
    videoUrlKey: "treatments.items.oncology.video_url",
    doctorIds: ["tamer_el_nahas", "hesham_elghazaly", "hatem_azim", "ahmed_elashry"],
    priceUSD: 3000,
  },
  {
    id: "joint_replacement",
    slug: "joint-replacement",
    sortOrder: 4,
    category: "ortho",
    titleKey: "treatments.items.joint_replacement.title",
    descriptionKey: "treatments.items.joint_replacement.description",
    bodyKey: "treatments.items.joint_replacement.body",
    doctorsKey: "treatments.items.joint_replacement.doctors",
    hospitalsKey: "treatments.items.joint_replacement.hospitals",
    techniquesKey: "treatments.items.joint_replacement.techniques",
    successRateKey: "treatments.items.joint_replacement.success_rate",
    videoUrlKey: "treatments.items.joint_replacement.video_url",
    doctorIds: ["mahmoud_hafez", "fouad_zamel_sadek"],
    priceUSD: 5500,
  },
  {
    id: "knee_replacement",
    slug: "knee-replacement",
    sortOrder: 5,
    category: "ortho",
    titleKey: "treatments.items.knee_replacement.title",
    descriptionKey: "treatments.items.knee_replacement.description",
    bodyKey: "treatments.items.knee_replacement.body",
    doctorsKey: "treatments.items.knee_replacement.doctors",
    hospitalsKey: "treatments.items.knee_replacement.hospitals",
    techniquesKey: "treatments.items.knee_replacement.techniques",
    successRateKey: "treatments.items.knee_replacement.success_rate",
    videoUrlKey: "treatments.items.knee_replacement.video_url",
    doctorIds: ["mahmoud_hafez", "fouad_zamel_sadek"],
    priceUSD: 4800,
  },
  {
    id: "limb_lengthening",
    slug: "limb-lengthening",
    sortOrder: 6,
    category: "ortho",
    titleKey: "treatments.items.limb_lengthening.title",
    descriptionKey: "treatments.items.limb_lengthening.description",
    bodyKey: "treatments.items.limb_lengthening.body",
    doctorsKey: "treatments.items.limb_lengthening.doctors",
    hospitalsKey: "treatments.items.limb_lengthening.hospitals",
    techniquesKey: "treatments.items.limb_lengthening.techniques",
    successRateKey: "treatments.items.limb_lengthening.success_rate",
    doctorIds: ["mahmoud_hafez", "mohamed_fawzy_khattab"],
    priceUSD: 5000,
  },
  {
    id: "spine_surgery",
    slug: "spine-surgery",
    sortOrder: 7,
    category: "ortho",
    titleKey: "treatments.items.spine_surgery.title",
    descriptionKey: "treatments.items.spine_surgery.description",
    bodyKey: "treatments.items.spine_surgery.body",
    doctorsKey: "treatments.items.spine_surgery.doctors",
    hospitalsKey: "treatments.items.spine_surgery.hospitals",
    techniquesKey: "treatments.items.spine_surgery.techniques",
    successRateKey: "treatments.items.spine_surgery.success_rate",
    videoUrlKey: "treatments.items.spine_surgery.video_url",
    doctorIds: ["mohamed_fawzy_khattab", "mohamed_mohi_eldin"],
    priceUSD: 4500,
  },
  {
    id: "addiction",
    slug: "addiction",
    sortOrder: 8,
    category: "general",
    titleKey: "treatments.items.addiction.title",
    descriptionKey: "treatments.items.addiction.description",
    bodyKey: "treatments.items.addiction.body",
    doctorsKey: "treatments.items.addiction.doctors",
    hospitalsKey: "treatments.items.addiction.hospitals",
    techniquesKey: "treatments.items.addiction.techniques",
    successRateKey: "treatments.items.addiction.success_rate",
    videoUrlKey: "treatments.items.addiction.video_url",
    doctorIds: ["nasser_loza", "mohamed_hossam_eldin"],
    priceUSD: 2000,
  },
  {
    id: "breast_augmentation",
    slug: "breast-augmentation",
    sortOrder: 9,
    category: "cosmetic",
    titleKey: "treatments.items.breast_augmentation.title",
    descriptionKey: "treatments.items.breast_augmentation.description",
    bodyKey: "treatments.items.breast_augmentation.body",
    doctorsKey: "treatments.items.breast_augmentation.doctors",
    hospitalsKey: "treatments.items.breast_augmentation.hospitals",
    techniquesKey: "treatments.items.breast_augmentation.techniques",
    successRateKey: "treatments.items.breast_augmentation.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 2500,
  },
  {
    id: "bbl",
    slug: "bbl",
    sortOrder: 10,
    category: "cosmetic",
    titleKey: "treatments.items.bbl.title",
    descriptionKey: "treatments.items.bbl.description",
    bodyKey: "treatments.items.bbl.body",
    doctorsKey: "treatments.items.bbl.doctors",
    hospitalsKey: "treatments.items.bbl.hospitals",
    techniquesKey: "treatments.items.bbl.techniques",
    successRateKey: "treatments.items.bbl.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 2800,
  },
  {
    id: "gynecomastia",
    slug: "gynecomastia",
    sortOrder: 11,
    category: "cosmetic",
    titleKey: "treatments.items.gynecomastia.title",
    descriptionKey: "treatments.items.gynecomastia.description",
    bodyKey: "treatments.items.gynecomastia.body",
    doctorsKey: "treatments.items.gynecomastia.doctors",
    hospitalsKey: "treatments.items.gynecomastia.hospitals",
    techniquesKey: "treatments.items.gynecomastia.techniques",
    successRateKey: "treatments.items.gynecomastia.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 1500,
  },
  {
    id: "vaser_liposuction",
    slug: "vaser-liposuction",
    sortOrder: 12,
    category: "cosmetic",
    titleKey: "treatments.items.vaser_liposuction.title",
    descriptionKey: "treatments.items.vaser_liposuction.description",
    bodyKey: "treatments.items.vaser_liposuction.body",
    doctorsKey: "treatments.items.vaser_liposuction.doctors",
    hospitalsKey: "treatments.items.vaser_liposuction.hospitals",
    techniquesKey: "treatments.items.vaser_liposuction.techniques",
    successRateKey: "treatments.items.vaser_liposuction.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 1800,
  },
  {
    id: "cosmetic",
    slug: "cosmetic",
    sortOrder: 13,
    category: "cosmetic",
    titleKey: "treatments.items.cosmetic.title",
    descriptionKey: "treatments.items.cosmetic.description",
    bodyKey: "treatments.items.cosmetic.body",
    doctorsKey: "treatments.items.cosmetic.doctors",
    hospitalsKey: "treatments.items.cosmetic.hospitals",
    techniquesKey: "treatments.items.cosmetic.techniques",
    successRateKey: "treatments.items.cosmetic.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 2000,
  },
  {
    id: "dental",
    slug: "dental",
    sortOrder: 14,
    category: "dental",
    titleKey: "treatments.items.dental.title",
    descriptionKey: "treatments.items.dental.description",
    bodyKey: "treatments.items.dental.body",
    doctorsKey: "treatments.items.dental.doctors",
    hospitalsKey: "treatments.items.dental.hospitals",
    techniquesKey: "treatments.items.dental.techniques",
    successRateKey: "treatments.items.dental.success_rate",
    videoUrlKey: "treatments.items.dental.video_url",
    doctorIds: ["john_elia", "ahmed_saeed"],
    priceUSD: 800,
  },
  {
    id: "hair_transplant",
    slug: "hair-transplant",
    sortOrder: 15,
    category: "cosmetic",
    titleKey: "treatments.items.hair_transplant.title",
    descriptionKey: "treatments.items.hair_transplant.description",
    bodyKey: "treatments.items.hair_transplant.body",
    doctorsKey: "treatments.items.hair_transplant.doctors",
    hospitalsKey: "treatments.items.hair_transplant.hospitals",
    techniquesKey: "treatments.items.hair_transplant.techniques",
    successRateKey: "treatments.items.hair_transplant.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 1850,
  },
  {
    id: "plastic_surgery",
    slug: "plastic-surgery",
    sortOrder: 16,
    category: "cosmetic",
    titleKey: "treatments.items.plastic_surgery.title",
    descriptionKey: "treatments.items.plastic_surgery.description",
    bodyKey: "treatments.items.plastic_surgery.body",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 2700,
  },
  {
    id: "cardiology",
    slug: "cardiology",
    sortOrder: 17,
    category: "specialized",
    titleKey: "treatments.items.cardiology.title",
    descriptionKey: "treatments.items.cardiology.description",
    bodyKey: "treatments.items.cardiology.body",
    doctorsKey: "treatments.items.cardiology.doctors",
    hospitalsKey: "treatments.items.cardiology.hospitals",
    techniquesKey: "treatments.items.cardiology.techniques",
    successRateKey: "treatments.items.cardiology.success_rate",
    videoUrlKey: "treatments.items.cardiology.video_url",
    doctorIds: ["ahmed_rezk", "mohamed_al_ghannam", "hossam_fathi"],
    priceUSD: 4000,
  },
  {
    id: "neurology",
    slug: "neurology",
    sortOrder: 18,
    category: "specialized",
    titleKey: "treatments.items.neurology.title",
    descriptionKey: "treatments.items.neurology.description",
    bodyKey: "treatments.items.neurology.body",
    doctorsKey: "treatments.items.neurology.doctors",
    hospitalsKey: "treatments.items.neurology.hospitals",
    techniquesKey: "treatments.items.neurology.techniques",
    successRateKey: "treatments.items.neurology.success_rate",
    doctorIds: ["magd_zakaria", "ahmed_elbassiouny", "walid_elhalaby"],
    priceUSD: 1500,
  },
  {
    id: "eye_surgery",
    slug: "eye-surgery",
    sortOrder: 19,
    category: "specialized",
    titleKey: "treatments.items.eye_surgery.title",
    descriptionKey: "treatments.items.eye_surgery.description",
    bodyKey: "treatments.items.eye_surgery.body",
    doctorsKey: "treatments.items.eye_surgery.doctors",
    hospitalsKey: "treatments.items.eye_surgery.hospitals",
    techniquesKey: "treatments.items.eye_surgery.techniques",
    successRateKey: "treatments.items.eye_surgery.success_rate",
    videoUrlKey: "treatments.items.eye_surgery.video_url",
    doctorIds: ["ahmad_khalil", "hazem_helmy"],
    priceUSD: 1000,
  },
  {
    id: "bariatric",
    slug: "bariatric",
    sortOrder: 20,
    category: "specialized",
    titleKey: "treatments.items.bariatric.title",
    descriptionKey: "treatments.items.bariatric.description",
    bodyKey: "treatments.items.bariatric.body",
    doctorsKey: "treatments.items.bariatric.doctors",
    hospitalsKey: "treatments.items.bariatric.hospitals",
    techniquesKey: "treatments.items.bariatric.techniques",
    successRateKey: "treatments.items.bariatric.success_rate",
    videoUrlKey: "treatments.items.bariatric.video_url",
    doctorIds: ["mahmoud_zakaria", "tamer_abdelbaki"],
    priceUSD: 3000,
  },
];

export async function listTreatments(options?: {
  simulateDelay?: boolean;
}): Promise<Treatment[]> {
  await applyMockDelay(options?.simulateDelay);
  return [...TREATMENTS].sort((a, b) => a.sortOrder - b.sortOrder);
}

export async function getTreatmentBySlug(
  slug: string,
  options?: { simulateDelay?: boolean },
): Promise<Treatment | undefined> {
  await applyMockDelay(options?.simulateDelay);
  return TREATMENTS.find((t) => t.slug === slug);
}

/** Sync read for quotation wizard / pricing (no mock delay). */
export function getTreatmentBySlugSync(slug: string): Treatment | undefined {
  return TREATMENTS.find((t) => t.slug === slug);
}
