import type { Treatment } from "@/types";
import { applyMockDelay } from "./mock-delay";

const TREATMENTS: Treatment[] = [
  {
    id: "diabetic_foot",
    slug: "diabetic-foot",
    sortOrder: 1,
    category: "general",
    titleKey: "treatments.items.diabetic_foot.title",
    descriptionKey: "treatments.items.diabetic_foot.description",
    bodyKey: "treatments.items.diabetic_foot.body",
    doctorsKey: "treatments.items.diabetic_foot.doctors",
    hospitalsKey: "treatments.items.diabetic_foot.hospitals",
    techniquesKey: "treatments.items.diabetic_foot.techniques",
    successRateKey: "treatments.items.diabetic_foot.success_rate",
    videoUrlKey: "treatments.items.diabetic_foot.video_url",
    doctorIds: ["rashad_bishara", "ayman_samadony", "hussein_alwan"],
  },
  {
    id: "ivf",
    slug: "ivf",
    sortOrder: 2,
    category: "general",
    titleKey: "treatments.items.ivf.title",
    descriptionKey: "treatments.items.ivf.description",
    bodyKey: "treatments.items.ivf.body",
    doctorsKey: "treatments.items.ivf.doctors",
    hospitalsKey: "treatments.items.ivf.hospitals",
    techniquesKey: "treatments.items.ivf.techniques",
    successRateKey: "treatments.items.ivf.success_rate",
    videoUrlKey: "treatments.items.ivf.video_url",
    doctorIds: ["mohamed_aboulghar", "sherif_pasha", "ismail_aboul_fotouh"],
  },
  {
    id: "oncology",
    slug: "oncology",
    sortOrder: 3,
    category: "general",
    titleKey: "treatments.items.oncology.title",
    descriptionKey: "treatments.items.oncology.description",
    bodyKey: "treatments.items.oncology.body",
    doctorsKey: "treatments.items.oncology.doctors",
    hospitalsKey: "treatments.items.oncology.hospitals",
    techniquesKey: "treatments.items.oncology.techniques",
    successRateKey: "treatments.items.oncology.success_rate",
    videoUrlKey: "treatments.items.oncology.video_url",
    doctorIds: ["tamer_el_nahas"],
  },
  {
    id: "joint_replacement",
    slug: "joint-replacement",
    sortOrder: 4,
    category: "ortho",
    titleKey: "treatments.items.joint_replacement.title",
    descriptionKey: "treatments.items.joint_replacement.description",
    bodyKey: "treatments.items.joint_replacement.body",
    doctorsKey: "treatments.items.joint_replacement.doctors",
    hospitalsKey: "treatments.items.joint_replacement.hospitals",
    techniquesKey: "treatments.items.joint_replacement.techniques",
    successRateKey: "treatments.items.joint_replacement.success_rate",
    videoUrlKey: "treatments.items.joint_replacement.video_url",
    doctorIds: ["mahmoud_hafez"],
    priceUSD: 4600,
  },
  {
    id: "knee_replacement",
    slug: "knee-replacement",
    sortOrder: 5,
    category: "ortho",
    titleKey: "treatments.items.knee_replacement.title",
    descriptionKey: "treatments.items.knee_replacement.description",
    bodyKey: "treatments.items.knee_replacement.body",
    priceUSD: 600,
  },
  {
    id: "limb_lengthening",
    slug: "limb-lengthening",
    sortOrder: 6,
    category: "ortho",
    titleKey: "treatments.items.limb_lengthening.title",
    descriptionKey: "treatments.items.limb_lengthening.description",
    bodyKey: "treatments.items.limb_lengthening.body",
    priceUSD: 2000,
  },
  {
    id: "spine_surgery",
    slug: "spine-surgery",
    sortOrder: 7,
    category: "ortho",
    titleKey: "treatments.items.spine_surgery.title",
    descriptionKey: "treatments.items.spine_surgery.description",
    bodyKey: "treatments.items.spine_surgery.body",
    priceUSD: 700,
  },
  {
    id: "addiction",
    slug: "addiction",
    sortOrder: 8,
    category: "general",
    titleKey: "treatments.items.addiction.title",
    descriptionKey: "treatments.items.addiction.description",
    bodyKey: "treatments.items.addiction.body",
    doctorsKey: "treatments.items.addiction.doctors",
    hospitalsKey: "treatments.items.addiction.hospitals",
    techniquesKey: "treatments.items.addiction.techniques",
    successRateKey: "treatments.items.addiction.success_rate",
    videoUrlKey: "treatments.items.addiction.video_url",
    doctorIds: ["nasser_loza"],
  },
  {
    id: "breast_augmentation",
    slug: "breast-augmentation",
    sortOrder: 9,
    category: "cosmetic",
    titleKey: "treatments.items.breast_augmentation.title",
    descriptionKey: "treatments.items.breast_augmentation.description",
    bodyKey: "treatments.items.breast_augmentation.body",
    priceUSD: 600,
  },
  {
    id: "bbl",
    slug: "bbl",
    sortOrder: 10,
    category: "cosmetic",
    titleKey: "treatments.items.bbl.title",
    descriptionKey: "treatments.items.bbl.description",
    bodyKey: "treatments.items.bbl.body",
    priceUSD: 700,
  },
  {
    id: "gynecomastia",
    slug: "gynecomastia",
    sortOrder: 11,
    category: "cosmetic",
    titleKey: "treatments.items.gynecomastia.title",
    descriptionKey: "treatments.items.gynecomastia.description",
    bodyKey: "treatments.items.gynecomastia.body",
    priceUSD: 600,
  },
  {
    id: "vaser_liposuction",
    slug: "vaser-liposuction",
    sortOrder: 12,
    category: "cosmetic",
    titleKey: "treatments.items.vaser_liposuction.title",
    descriptionKey: "treatments.items.vaser_liposuction.description",
    bodyKey: "treatments.items.vaser_liposuction.body",
    priceUSD: 1000,
  },
  {
    id: "cosmetic",
    slug: "cosmetic",
    sortOrder: 13,
    category: "cosmetic",
    titleKey: "treatments.items.cosmetic.title",
    descriptionKey: "treatments.items.cosmetic.description",
    bodyKey: "treatments.items.cosmetic.body",
  },
];

export async function listTreatments(options?: {
  simulateDelay?: boolean;
}): Promise<Treatment[]> {
  await applyMockDelay(options?.simulateDelay);
  return [...TREATMENTS].sort((a, b) => a.sortOrder - b.sortOrder);
}

export async function getTreatmentBySlug(
  slug: string,
  options?: { simulateDelay?: boolean },
): Promise<Treatment | undefined> {
  await applyMockDelay(options?.simulateDelay);
  return TREATMENTS.find((t) => t.slug === slug);
}
