import type { Treatment } from "@/types";
import { applyMockDelay } from "./mock-delay";

const TREATMENTS: Treatment[] = [
  {
    id: "diabetic_foot",
    slug: "diabetic-foot",
    sortOrder: 1,
    category: "general",
    titleKey: "treatments.items.diabetic_foot.title",
    descriptionKey: "treatments.items.diabetic_foot.description",
    bodyKey: "treatments.items.diabetic_foot.body",
    doctorsKey: "treatments.items.diabetic_foot.doctors",
    hospitalsKey: "treatments.items.diabetic_foot.hospitals",
    techniquesKey: "treatments.items.diabetic_foot.techniques",
    successRateKey: "treatments.items.diabetic_foot.success_rate",
    videoUrlKey: "treatments.items.diabetic_foot.video_url",
    doctorIds: ["rashad_bishara", "ayman_samadony", "hussein_alwan"],
    priceUSD: 1500,
  },
  {
    id: "ivf",
    slug: "ivf",
    sortOrder: 2,
    category: "general",
    titleKey: "treatments.items.ivf.title",
    descriptionKey: "treatments.items.ivf.description",
    bodyKey: "treatments.items.ivf.body",
    doctorsKey: "treatments.items.ivf.doctors",
    hospitalsKey: "treatments.items.ivf.hospitals",
    techniquesKey: "treatments.items.ivf.techniques",
    successRateKey: "treatments.items.ivf.success_rate",
    videoUrlKey: "treatments.items.ivf.video_url",
    doctorIds: ["mohamed_aboulghar", "maged_adel_aziz"],
    priceUSD: 600,
  },
  {
    id: "oncology",
    slug: "oncology",
    sortOrder: 3,
    category: "general",
    titleKey: "treatments.items.oncology.title",
    descriptionKey: "treatments.items.oncology.description",
    bodyKey: "treatments.items.oncology.body",
    doctorsKey: "treatments.items.oncology.doctors",
    hospitalsKey: "treatments.items.oncology.hospitals",
    techniquesKey: "treatments.items.oncology.techniques",
    successRateKey: "treatments.items.oncology.success_rate",
    videoUrlKey: "treatments.items.oncology.video_url",
    doctorIds: ["tamer_el_nahas", "hesham_elghazaly", "hatem_azim", "ahmed_elashry"],
    priceUSD: 3000,
  },
  {
    id: "joint_replacement",
    slug: "joint-replacement",
    sortOrder: 4,
    category: "ortho",
    titleKey: "treatments.items.joint_replacement.title",
    descriptionKey: "treatments.items.joint_replacement.description",
    bodyKey: "treatments.items.joint_replacement.body",
    doctorsKey: "treatments.items.joint_replacement.doctors",
    hospitalsKey: "treatments.items.joint_replacement.hospitals",
    techniquesKey: "treatments.items.joint_replacement.techniques",
    successRateKey: "treatments.items.joint_replacement.success_rate",
    videoUrlKey: "treatments.items.joint_replacement.video_url",
    doctorIds: ["mahmoud_hafez", "fouad_zamel_sadek"],
    priceUSD: 600,
  },
  {
    id: "knee_replacement",
    slug: "knee-replacement",
    sortOrder: 5,
    category: "ortho",
    titleKey: "treatments.items.knee_replacement.title",
    descriptionKey: "treatments.items.knee_replacement.description",
    bodyKey: "treatments.items.knee_replacement.body",
    doctorsKey: "treatments.items.knee_replacement.doctors",
    hospitalsKey: "treatments.items.knee_replacement.hospitals",
    techniquesKey: "treatments.items.knee_replacement.techniques",
    successRateKey: "treatments.items.knee_replacement.success_rate",
    videoUrlKey: "treatments.items.knee_replacement.video_url",
    doctorIds: ["mahmoud_hafez", "fouad_zamel_sadek"],
    priceUSD: 600,
  },
  {
    id: "limb_lengthening",
    slug: "limb-lengthening",
    sortOrder: 6,
    category: "ortho",
    titleKey: "treatments.items.limb_lengthening.title",
    descriptionKey: "treatments.items.limb_lengthening.description",
    bodyKey: "treatments.items.limb_lengthening.body",
    doctorsKey: "treatments.items.limb_lengthening.doctors",
    hospitalsKey: "treatments.items.limb_lengthening.hospitals",
    techniquesKey: "treatments.items.limb_lengthening.techniques",
    successRateKey: "treatments.items.limb_lengthening.success_rate",
    doctorIds: ["mahmoud_hafez", "mohamed_fawzy_khattab"],
    priceUSD: 2000,
  },
  {
    id: "spine_surgery",
    slug: "spine-surgery",
    sortOrder: 7,
    category: "ortho",
    titleKey: "treatments.items.spine_surgery.title",
    descriptionKey: "treatments.items.spine_surgery.description",
    bodyKey: "treatments.items.spine_surgery.body",
    doctorsKey: "treatments.items.spine_surgery.doctors",
    hospitalsKey: "treatments.items.spine_surgery.hospitals",
    techniquesKey: "treatments.items.spine_surgery.techniques",
    successRateKey: "treatments.items.spine_surgery.success_rate",
    videoUrlKey: "treatments.items.spine_surgery.video_url",
    doctorIds: ["mohamed_fawzy_khattab", "mohamed_mohi_eldin"],
    priceUSD: 700,
  },
  {
    id: "addiction",
    slug: "addiction",
    sortOrder: 8,
    category: "mental",
    titleKey: "treatments.items.addiction.title",
    descriptionKey: "treatments.items.addiction.description",
    bodyKey: "treatments.items.addiction.body",
    doctorsKey: "treatments.items.addiction.doctors",
    hospitalsKey: "treatments.items.addiction.hospitals",
    techniquesKey: "treatments.items.addiction.techniques",
    successRateKey: "treatments.items.addiction.success_rate",
    videoUrlKey: "treatments.items.addiction.video_url",
    doctorIds: ["nasser_loza", "mohamed_hossam_eldin"],
    priceUSD: 2000,
  },
  {
    id: "autism",
    slug: "autism",
    sortOrder: 32,
    category: "mental",
    titleKey: "treatments.items.autism.title",
    descriptionKey: "treatments.items.autism.description",
    bodyKey: "treatments.items.autism.body",
    doctorsKey: "treatments.items.autism.doctors",
    hospitalsKey: "treatments.items.autism.hospitals",
    techniquesKey: "treatments.items.autism.techniques",
    successRateKey: "treatments.items.autism.success_rate",
    doctorIds: ["nasser_loza", "mohamed_hossam_eldin"],
    priceUSD: 300,
  },
  {
    id: "breast_augmentation",
    slug: "breast-augmentation",
    sortOrder: 9,
    category: "cosmetic",
    titleKey: "treatments.items.breast_augmentation.title",
    descriptionKey: "treatments.items.breast_augmentation.description",
    bodyKey: "treatments.items.breast_augmentation.body",
    doctorsKey: "treatments.items.breast_augmentation.doctors",
    hospitalsKey: "treatments.items.breast_augmentation.hospitals",
    techniquesKey: "treatments.items.breast_augmentation.techniques",
    successRateKey: "treatments.items.breast_augmentation.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 600,
  },
  {
    id: "bbl",
    slug: "bbl",
    sortOrder: 10,
    category: "cosmetic",
    titleKey: "treatments.items.bbl.title",
    descriptionKey: "treatments.items.bbl.description",
    bodyKey: "treatments.items.bbl.body",
    doctorsKey: "treatments.items.bbl.doctors",
    hospitalsKey: "treatments.items.bbl.hospitals",
    techniquesKey: "treatments.items.bbl.techniques",
    successRateKey: "treatments.items.bbl.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 700,
  },
  {
    id: "gynecomastia",
    slug: "gynecomastia",
    sortOrder: 11,
    category: "cosmetic",
    titleKey: "treatments.items.gynecomastia.title",
    descriptionKey: "treatments.items.gynecomastia.description",
    bodyKey: "treatments.items.gynecomastia.body",
    doctorsKey: "treatments.items.gynecomastia.doctors",
    hospitalsKey: "treatments.items.gynecomastia.hospitals",
    techniquesKey: "treatments.items.gynecomastia.techniques",
    successRateKey: "treatments.items.gynecomastia.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 600,
  },
  {
    id: "vaser_liposuction",
    slug: "vaser-liposuction",
    sortOrder: 12,
    category: "cosmetic",
    titleKey: "treatments.items.vaser_liposuction.title",
    descriptionKey: "treatments.items.vaser_liposuction.description",
    bodyKey: "treatments.items.vaser_liposuction.body",
    doctorsKey: "treatments.items.vaser_liposuction.doctors",
    hospitalsKey: "treatments.items.vaser_liposuction.hospitals",
    techniquesKey: "treatments.items.vaser_liposuction.techniques",
    successRateKey: "treatments.items.vaser_liposuction.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 1000,
  },
  {
    id: "cosmetic",
    slug: "cosmetic",
    sortOrder: 13,
    category: "cosmetic",
    titleKey: "treatments.items.cosmetic.title",
    descriptionKey: "treatments.items.cosmetic.description",
    bodyKey: "treatments.items.cosmetic.body",
    doctorsKey: "treatments.items.cosmetic.doctors",
    hospitalsKey: "treatments.items.cosmetic.hospitals",
    techniquesKey: "treatments.items.cosmetic.techniques",
    successRateKey: "treatments.items.cosmetic.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 2000,
  },
  {
    id: "dental",
    slug: "dental",
    sortOrder: 14,
    category: "dental",
    titleKey: "treatments.items.dental.title",
    descriptionKey: "treatments.items.dental.description",
    bodyKey: "treatments.items.dental.body",
    doctorsKey: "treatments.items.dental.doctors",
    hospitalsKey: "treatments.items.dental.hospitals",
    techniquesKey: "treatments.items.dental.techniques",
    successRateKey: "treatments.items.dental.success_rate",
    videoUrlKey: "treatments.items.dental.video_url",
    doctorIds: ["john_elia", "ahmed_saeed"],
    priceUSD: 40,
  },
  {
    id: "hair_transplant",
    slug: "hair-transplant",
    sortOrder: 15,
    category: "cosmetic",
    titleKey: "treatments.items.hair_transplant.title",
    descriptionKey: "treatments.items.hair_transplant.description",
    bodyKey: "treatments.items.hair_transplant.body",
    doctorsKey: "treatments.items.hair_transplant.doctors",
    hospitalsKey: "treatments.items.hair_transplant.hospitals",
    techniquesKey: "treatments.items.hair_transplant.techniques",
    successRateKey: "treatments.items.hair_transplant.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 200,
  },
  {
    id: "plastic_surgery",
    slug: "plastic-surgery",
    sortOrder: 16,
    category: "cosmetic",
    titleKey: "treatments.items.plastic_surgery.title",
    descriptionKey: "treatments.items.plastic_surgery.description",
    bodyKey: "treatments.items.plastic_surgery.body",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 700,
  },
  {
    id: "cardiology",
    slug: "cardiology",
    sortOrder: 17,
    category: "general",
    titleKey: "treatments.items.cardiology.title",
    descriptionKey: "treatments.items.cardiology.description",
    bodyKey: "treatments.items.cardiology.body",
    doctorsKey: "treatments.items.cardiology.doctors",
    hospitalsKey: "treatments.items.cardiology.hospitals",
    techniquesKey: "treatments.items.cardiology.techniques",
    successRateKey: "treatments.items.cardiology.success_rate",
    videoUrlKey: "treatments.items.cardiology.video_url",
    doctorIds: ["ahmed_rezk", "mohamed_al_ghannam", "hossam_fathi"],
    priceUSD: 4000,
  },
  {
    id: "neurology",
    slug: "neurology",
    sortOrder: 18,
    category: "general",
    titleKey: "treatments.items.neurology.title",
    descriptionKey: "treatments.items.neurology.description",
    bodyKey: "treatments.items.neurology.body",
    doctorsKey: "treatments.items.neurology.doctors",
    hospitalsKey: "treatments.items.neurology.hospitals",
    techniquesKey: "treatments.items.neurology.techniques",
    successRateKey: "treatments.items.neurology.success_rate",
    doctorIds: ["magd_zakaria", "ahmed_elbassiouny", "walid_elhalaby"],
    priceUSD: 1500,
  },
  {
    id: "eye_surgery",
    slug: "eye-surgery",
    sortOrder: 19,
    category: "general",
    titleKey: "treatments.items.eye_surgery.title",
    descriptionKey: "treatments.items.eye_surgery.description",
    bodyKey: "treatments.items.eye_surgery.body",
    doctorsKey: "treatments.items.eye_surgery.doctors",
    hospitalsKey: "treatments.items.eye_surgery.hospitals",
    techniquesKey: "treatments.items.eye_surgery.techniques",
    successRateKey: "treatments.items.eye_surgery.success_rate",
    videoUrlKey: "treatments.items.eye_surgery.video_url",
    doctorIds: ["ahmad_khalil", "hazem_helmy"],
    priceUSD: 1000,
  },
  {
    id: "bariatric",
    slug: "bariatric",
    sortOrder: 20,
    category: "general",
    titleKey: "treatments.items.bariatric.title",
    descriptionKey: "treatments.items.bariatric.description",
    bodyKey: "treatments.items.bariatric.body",
    doctorsKey: "treatments.items.bariatric.doctors",
    hospitalsKey: "treatments.items.bariatric.hospitals",
    techniquesKey: "treatments.items.bariatric.techniques",
    successRateKey: "treatments.items.bariatric.success_rate",
    videoUrlKey: "treatments.items.bariatric.video_url",
    doctorIds: ["mahmoud_zakaria", "tamer_abdelbaki"],
    priceUSD: 3000,
  },

  {
    id: "fue_extraction",
    slug: "fue-extraction",
    sortOrder: 21,
    category: "cosmetic",
    titleKey: "treatments.items.fue_extraction.title",
    descriptionKey: "treatments.items.fue_extraction.description",
    bodyKey: "treatments.items.fue_extraction.body",
    doctorsKey: "treatments.items.fue_extraction.doctors",
    hospitalsKey: "treatments.items.fue_extraction.hospitals",
    techniquesKey: "treatments.items.fue_extraction.techniques",
    successRateKey: "treatments.items.fue_extraction.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 600,
  },
  {
    id: "fut_transplantation",
    slug: "fut-transplantation",
    sortOrder: 22,
    category: "cosmetic",
    titleKey: "treatments.items.fut_transplantation.title",
    descriptionKey: "treatments.items.fut_transplantation.description",
    bodyKey: "treatments.items.fut_transplantation.body",
    doctorsKey: "treatments.items.fut_transplantation.doctors",
    hospitalsKey: "treatments.items.fut_transplantation.hospitals",
    techniquesKey: "treatments.items.fut_transplantation.techniques",
    successRateKey: "treatments.items.fut_transplantation.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 200,
  },
  {
    id: "dhi_implantation",
    slug: "dhi-implantation",
    sortOrder: 23,
    category: "cosmetic",
    titleKey: "treatments.items.dhi_implantation.title",
    descriptionKey: "treatments.items.dhi_implantation.description",
    bodyKey: "treatments.items.dhi_implantation.body",
    doctorsKey: "treatments.items.dhi_implantation.doctors",
    hospitalsKey: "treatments.items.dhi_implantation.hospitals",
    techniquesKey: "treatments.items.dhi_implantation.techniques",
    successRateKey: "treatments.items.dhi_implantation.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 500,
  },
  {
    id: "robotic_hair_transplant",
    slug: "robotic-hair-transplant",
    sortOrder: 24,
    category: "cosmetic",
    titleKey: "treatments.items.robotic_hair_transplant.title",
    descriptionKey: "treatments.items.robotic_hair_transplant.description",
    bodyKey: "treatments.items.robotic_hair_transplant.body",
    doctorsKey: "treatments.items.robotic_hair_transplant.doctors",
    hospitalsKey: "treatments.items.robotic_hair_transplant.hospitals",
    techniquesKey: "treatments.items.robotic_hair_transplant.techniques",
    successRateKey: "treatments.items.robotic_hair_transplant.success_rate",
    doctorIds: ["shady_el_maghraby", "marwan_noureldin"],
    priceUSD: 1600,
  },
  {
    id: "conventional_ivf",
    slug: "conventional-ivf",
    sortOrder: 25,
    category: "general",
    titleKey: "treatments.items.conventional_ivf.title",
    descriptionKey: "treatments.items.conventional_ivf.description",
    bodyKey: "treatments.items.conventional_ivf.body",
    doctorsKey: "treatments.items.conventional_ivf.doctors",
    hospitalsKey: "treatments.items.conventional_ivf.hospitals",
    techniquesKey: "treatments.items.conventional_ivf.techniques",
    successRateKey: "treatments.items.conventional_ivf.success_rate",
    doctorIds: ["mohamed_aboulghar", "maged_adel_aziz"],
    priceUSD: 600,
  },
  {
    id: "icsi",
    slug: "icsi",
    sortOrder: 26,
    category: "general",
    titleKey: "treatments.items.icsi.title",
    descriptionKey: "treatments.items.icsi.description",
    bodyKey: "treatments.items.icsi.body",
    doctorsKey: "treatments.items.icsi.doctors",
    hospitalsKey: "treatments.items.icsi.hospitals",
    techniquesKey: "treatments.items.icsi.techniques",
    successRateKey: "treatments.items.icsi.success_rate",
    doctorIds: ["mohamed_aboulghar", "maged_adel_aziz"],
    priceUSD: 600,
  },
  {
    id: "hip_replacement",
    slug: "hip-replacement",
    sortOrder: 27,
    category: "ortho",
    titleKey: "treatments.items.hip_replacement.title",
    descriptionKey: "treatments.items.hip_replacement.description",
    bodyKey: "treatments.items.hip_replacement.body",
    doctorsKey: "treatments.items.hip_replacement.doctors",
    hospitalsKey: "treatments.items.hip_replacement.hospitals",
    techniquesKey: "treatments.items.hip_replacement.techniques",
    successRateKey: "treatments.items.hip_replacement.success_rate",
    doctorIds: ["mahmoud_hafez", "fouad_zamel_sadek"],
    priceUSD: 4600,
  },
  {
    id: "lip_reduction",
    slug: "lip-reduction",
    sortOrder: 28,
    category: "cosmetic",
    titleKey: "treatments.items.lip_reduction.title",
    descriptionKey: "treatments.items.lip_reduction.description",
    bodyKey: "treatments.items.lip_reduction.body",
    doctorsKey: "treatments.items.lip_reduction.doctors",
    hospitalsKey: "treatments.items.lip_reduction.hospitals",
    techniquesKey: "treatments.items.lip_reduction.techniques",
    successRateKey: "treatments.items.lip_reduction.success_rate",
    doctorIds: ["yasser_badi", "mohamed_abdallah_tawfik"],
    priceUSD: 700,
  },
  {
    id: "dental_implants",
    slug: "dental-implants",
    sortOrder: 29,
    category: "dental",
    titleKey: "treatments.items.dental_implants.title",
    descriptionKey: "treatments.items.dental_implants.description",
    bodyKey: "treatments.items.dental_implants.body",
    doctorsKey: "treatments.items.dental_implants.doctors",
    hospitalsKey: "treatments.items.dental_implants.hospitals",
    techniquesKey: "treatments.items.dental_implants.techniques",
    successRateKey: "treatments.items.dental_implants.success_rate",
    doctorIds: ["john_elia", "ahmed_saeed"],
    priceUSD: 100,
  },
  {
    id: "dental_crowns_bridges",
    slug: "dental-crowns-bridges",
    sortOrder: 30,
    category: "dental",
    titleKey: "treatments.items.dental_crowns_bridges.title",
    descriptionKey: "treatments.items.dental_crowns_bridges.description",
    bodyKey: "treatments.items.dental_crowns_bridges.body",
    doctorsKey: "treatments.items.dental_crowns_bridges.doctors",
    hospitalsKey: "treatments.items.dental_crowns_bridges.hospitals",
    techniquesKey: "treatments.items.dental_crowns_bridges.techniques",
    successRateKey: "treatments.items.dental_crowns_bridges.success_rate",
    doctorIds: ["john_elia", "ahmed_saeed"],
    priceUSD: 40,
  },
  {
    id: "orthodontic_treatment",
    slug: "orthodontic-treatment",
    sortOrder: 31,
    category: "dental",
    titleKey: "treatments.items.orthodontic_treatment.title",
    descriptionKey: "treatments.items.orthodontic_treatment.description",
    bodyKey: "treatments.items.orthodontic_treatment.body",
    doctorsKey: "treatments.items.orthodontic_treatment.doctors",
    hospitalsKey: "treatments.items.orthodontic_treatment.hospitals",
    techniquesKey: "treatments.items.orthodontic_treatment.techniques",
    successRateKey: "treatments.items.orthodontic_treatment.success_rate",
    doctorIds: ["john_elia", "ahmed_saeed"],
    priceUSD: 600,
  },
];

export async function listTreatments(options?: {
  simulateDelay?: boolean;
}): Promise<Treatment[]> {
  await applyMockDelay(options?.simulateDelay);
  return [...TREATMENTS].sort((a, b) => a.sortOrder - b.sortOrder);
}

export async function getTreatmentBySlug(
  slug: string,
  options?: { simulateDelay?: boolean },
): Promise<Treatment | undefined> {
  await applyMockDelay(options?.simulateDelay);
  return TREATMENTS.find((t) => t.slug === slug);
}

/** Sync read for quotation wizard / pricing (no mock delay). */
export function getTreatmentBySlugSync(slug: string): Treatment | undefined {
  return TREATMENTS.find((t) => t.slug === slug);
}
